version: "3.8"
services:
    db:
        image: postgis/postgis:16-3.4
        container_name: postgres_postgis
        environment:
            POSTGRES_PASSWORD:
            POSTGRES_USER:
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
